export const CONSUMERS_IMPORT_INITIATE = 'CONSUMERS_IMPORT_INITIATE';
export const CONSUMERS_IMPORT_START = 'CONSUMERS_IMPORT_START';
export const CONSUMERS_IMPORT_SUCCESS = 'CONSUMERS_IMPORT_SUCCESS';
export const CONSUMERS_IMPORT_FAIL = 'CONSUMERS_IMPORT_FAIL';
export const CONSUMERS_UPDATE = 'CONSUMERS_UPDATE';
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';
